apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: 427107249392.dkr.ecr.us-east-1.amazonaws.com/payments:1.0
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-payments
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-payments
                  key: DB_PASSWORD
            - name: MP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-payments
                  key: MP_ACCESS_TOKEN
          envFrom:
            - configMapRef:
                name: cm-payments
          ports:
            - containerPort: 8080